config/routes.rb
Rails.application.routes.draw do
  devise_for :authors, :controllers => {registrations: 'registrations'}
  
  resources :authors
  root 'authors#index'
  
  resources :books
  root 'books#index'
  namespace :api do
    resources :authors, only: [:show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  before_create :set_api_key
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :date_of_birth, presence: true
  has_and_belongs_to_many :books

  private
  def generate_api_key
    SecureRandom.base58(24)
  end

  def set_api_key
    self.api_key = generate_api_key
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :book_title, presence: true
  validates :author_id, presence: true
  has_and_belongs_to_many :authors
end

app/controllers/api/authors_controller.rb
module Api
  class AuthorsController < BaseApiController
    def show
      author = Author.find([:id])
      render json: author, adapter: :json, status: 201
    end
  end
end

app/controllers/api/base_api_controller.rb
module Api
  class BaseApiController < ActionController::API
    before_action :authenticate!

    private
    def authenticate!
      if Author.find_by(api_key: request.headers['Authorization'])
        return true
      else
        render json: {message: I18n.t('unauthorized') }, status: :unauthorized
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
before_action :authenticate_author!, except: [:index]
  def index
    @authors = Author.all
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      flash[:success] = t('updated_successfuly')
      redirect_to authors_path(@author)
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
  end

  private
    def author_params
      params.require(:author).permit(:email, :first_name, :last_name, :date_of_birth, :password, :api_key, :password_confirmation)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_author!, except: [:index]
  def index
    @books = Book.all
  end

  def new
    @book = current_author.books.build
  end
 
  def create
    @book = current_author.books.build(book_params)
    if @book.save
      flash[:success] = t('created_successfully')
      redirect_to books_path(@book)
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = t('updated_successfuly')
      redirect_to books_path(@book)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
  end

  private
    def book_params
      params.require(:book).permit(:author_id, :book_title)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 private
  def sign_up_params
    params.require(:author).permit(:email, :first_name, :last_name, :date_of_birth, :password, :password_confirmation)
  end 

  def account_update_params
    params.require(:author).permit(:email, :first_name, :last_name, :date_of_birth, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/authors/edit.html.erb
<h1> Edit Author</h1>
<%= form_for @author do |f| %>
<p>
  <%= f.label :First_Name %> <br>
  <%= f.text_area :first_name %>
</p>
<p>
  <%= f.label :Last_Name %> <br>
  <%= f.text_area :last_name %>
</p>
<p>
  <%= f.label :Date_of_Birth %> <br>
  <%= f.text_area :date_of_birth %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/authors/index.html.erb
<table>
  <h1>List Authors</h1>
  <% @authors.each do |author| %>
    <tr>
      <td>First Name: <%= author.first_name %></td>
    </tr>
    <tr>
      <td>Last Name <%= author.last_name %></td>
    </tr>
    <tr>
      <td>Date of Birth <%= author.date_of_birth %></td>
    </tr>
    <td><%= link_to 'Edit', edit_author_path(author) %>
    <%= link_to 'Destroy', author_path(author), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to 'New Book', new_book_path %>

app/views/books/edit.html.erb
<h1> Edit Book Title</h1>
<%= form_for @book do |f| %>
<p>
  <%= f.label :Book_Title %> <br>
  <%= f.text_area :book_title %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/books/index.html.erb
<table>
  <h1>List Books</h1>
  <% @books.each do |book| %>
    <tr>
      <td>Book Title: <%= book.book_title %></td>
    </tr>
    <td><%= link_to 'Edit', edit_book_path(book) %>
    <%= link_to 'Destroy', book_path(book), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1> New Book</h1>
<%= form_for @book do |f| %>
<p>
  <%= f.label :Book_Title %> <br>
  <%= f.text_area :book_title %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>
<td><%= link_to 'List Books', books_path %>
<td><%= link_to 'List Author Details', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "button is-info is-inverted"%>
    </p>
    <%= yield %>
  </body>
</html>